DROP TABLE "TTEM" 
  
CREATE TABLE "ITEM" 
(	"ID" NUMBER Generated AS IDENTITY, 
"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
"ATTACK" NUMBER DEFAULT 0, 
"ADDATTACK" NUMBER DEFAULT 0, 
"COUNT" NUMBER DEFAULT 0, 
"LIMIT" VARCHAR2(20 BYTE), 
"TIMES" NUMBER DEFAULT 1, 
"USE" NUMBER DEFAULT 0, 
"NEEDDICE" NUMBER DEFAULT 0, 
"ACTIVELIMIT" VARCHAR2(20 BYTE), 
"FIRESTACK" NUMBER DEFAULT 0, 
"ICESTACK" NUMBER DEFAULT 0, 
"ELECSTACK" NUMBER DEFAULT 0, 
"POISONSTACK" NUMBER DEFAULT 0, 
"RECOVERY" NUMBER DEFAULT 0, 
"DEFENCE" NUMBER DEFAULT 0, 
"DAMAGE" NUMBER DEFAULT 0, 
"NEWDICE" VARCHAR2(20 BYTE), 
"ACCUMULATION" NUMBER DEFAULT 0, 
 CONSTRAINT "ITEM_PK" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "USERS" ;
